spring.application.name=UberApp

# database configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.postgis.PostgisDialect

#spring.jpa.defer-datasource-initialization=false

#spring.datasource.initialization-mode = always;
#spring.sql.init.data-locations=classpath:data.sql



# distance multiplier --> used in com.uber.services.CalculateFairStrategy
distanceService.perKm.multiplier = 10

# actuator configuration
management.endpoints.web.exposure.include=*

management.info.env.enabled = true
info.app.author=kartik
info.app.company=uber

springdoc.swagger-ui.enabled=true


#smtp configs
# Email configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummyhotemail@gmail.com
spring.mail.password=nclo gdbc uzcb lxia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true






