package com.uber.security;


import io.jsonwebtoken.Claims;
import io.jsonwebtoken.SignatureAlgorithm;
import org.jetbrains.annotations.NotNull;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Service;

import java.security.Key;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;



@Service
public class JwtService {

    private static final String SECRET_KEY = "JEBSCYETR8F7I83WU4EH9NBCDWSIWEUHD8WEHSHSDIHW983YEHWBJBBSJDBHHEWIHY387YHQEWYIHBDIY2H8UDHQWBSHBIWQHDUIhwe8uhd8u2hwiwxbneihbhdwuhediewidhewdyhw";

    public String generatoken(Map<String,Object> extraClaims , @NotNull UserDetails userDetails){

        String username = userDetails.getUsername();

        return Jwts.builder()
                .claims(extraClaims)
                .subject(username)
                .signWith(getSignInKey(), SignatureAlgorithm.HS256)
                .issuedAt(new Date(System.currentTimeMillis()))
                .expiration(new Date(System.currentTimeMillis() + (1000 * 60*60)))
                .compact();


    }

    public String generateRefreshToken(UserDetails userDetails){

        String username = userDetails.getUsername();


        return Jwts.builder()
                .subject(username)
                .signWith(getSignInKey(),SignatureAlgorithm.HS256)
                .issuedAt(new Date(System.currentTimeMillis()))
                .expiration(new Date(System.currentTimeMillis()+(1000*60*60*24*7)))
                .compact();
    }

    public String generateToken(UserDetails userDetails){
//        if we want to generate only on the basis of userdetails not on the basis of extraClaims

        return generatoken(new HashMap<>(),userDetails);
    }

    public boolean isTokenValid(String token , UserDetails userDetails){
        String username = extractUsername(token);

        return username.equals(userDetails.getUsername())&&(!isTokenExpired(token));
    }

    private boolean isTokenExpired(String token) {
        Date expirationDate = getTokenExpirationDate(token);

        return expirationDate.before(new Date());
    }

    private Date getTokenExpirationDate(String token) {
        return extractClaims(token,Claims -> Claims.getExpiration());
    }


    public String extractUsername(String jwtToken) {



        String email = extractClaims(jwtToken , Claims ->Claims.getSubject());
        return email;
    }

    public <T> T extractClaims(String token , Function<Claims,T> claimResolver){
        final Claims claims = extractAllClaims(token);
        return  claimResolver.apply(claims);

//        The extractClaims method uses Java's functional programming to provide flexibility. The Function<Claims, T> is a functional interface that takes a Claims object as input and produces a result (T), allowing you to define any custom logic for extracting claims.
//
//For example:
//
//    If you want to extract the subject (sub) of the JWT, you can pass Claims::getSubject.
//    If you want to extract a custom claim like role, you can pass a lambda function like claims -> claims.get("role", String.class).
    }

    private Claims extractAllClaims(String token){

//        It takes a token (the JWT string) as input. This is typically passed as a Bearer token in the Authorization header of an HTTP request.
//        validates the token and extract claims such as username,email,role etc

        return Jwts.parser()                                           //Jwts.parserBuilder() creates a parser object that is configured to parse and validate JWTs.
                .setSigningKey(getSignInKey())                    //.setSigningKey(getSignInKey()) configures the parser with the cryptographic key required to verify the JWT's signature.
                .build().parseClaimsJws(token)                         //The signing key is generated by the getSignInKey() method, which decodes the Base64-encoded SECRET_KEY and converts it into a cryptographic HMAC key.
                .getBody();

        //.build().parseClaimsJws(token):
        //
        //    Parses the JWT token.
        //    Verifies the signature using the signing key.
        //    Validates the structure of the token (header, payload, and signature).
        //    If the token is invalid (e.g., expired, malformed, or tampered with), an exception (like JwtException) is thrown.
        //    .getBody() extracts the claims (the payload part of the JWT) if the token is valid.
        //    The claims are returned as a Claims object, which is essentially a map-like structure containing key-value pairs of the data embedded in the JWT.
    }

    private Key getSignInKey() {

        byte[] keyBytes = Decoders.BASE64.decode(SECRET_KEY);

        return Keys.hmacShaKeyFor(keyBytes);
    }
}

